# Import necessary library

In [3]:
import numpy as np

# 3.9a Matrix (2D array)

In [7]:
# Matrix (2D array)
matrix = np.array([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

Matrix:
 [[1 2]
 [3 4]]


# 3.9b Column matrix (or column vector)

In [11]:
# Column matrix (or column vector)
column_matrix = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])  # This creates a 4x1 column matrix
print("Column Matrix:\n", column_matrix)

Column Matrix:
 [[1]
 [2]
 [3]
 [4]]


# 3.9c Row matrix (or row vector)

In [15]:
# Row matrix (or row vector)
row_matrix = np.array([[1, 2, 3, 4]])  # This creates a 1x4 row matrix
print("Row Matrix:\n", row_matrix)

Row Matrix:
 [[1 2 3 4]]


# 3.9d Scalar

In [19]:
# Scalar
scalar = 5
print("Scalar:", scalar)

Scalar: 5


# 3.9e Rectangular matrix

In [23]:
# Rectangular matrix
rectangular_matrix = np.array([[1, 2, 3], [4, 5, 6]])  # This creates a 2x3 matrix
print("Rectangular Matrix:\n", rectangular_matrix)

Rectangular Matrix:
 [[1 2 3]
 [4 5 6]]


# 3.9f Square matrix

In [27]:
# Square matrix
square_matrix = np.array([[1, 2], [3, 4]])
print("Square Matrix:\n", square_matrix)

Square Matrix:
 [[1 2]
 [3 4]]


# 3.9g Diagonal matrix

In [31]:
# Diagonal matrix
diagonal_matrix = np.diag([1, 2, 3])
print("Diagonal Matrix:\n", diagonal_matrix)

Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


# 3.9h Scalar matrix

In [35]:
# Scalar matrix
scalar_value = 5
scalar_matrix = np.array([[scalar_value, 0, 0], 
                          [0, scalar_value, 0], 
                          [0, 0, scalar_value]])  # This creates a 3x3 scalar matrix
print("Scalar Matrix:\n", scalar_matrix)

Scalar Matrix:
 [[5 0 0]
 [0 5 0]
 [0 0 5]]


# 3.9i Identity or unit matrix

In [39]:
# Identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 3.9j Upper triangular matrix

In [43]:
# Upper triangular matrix
A = np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]])
print("Upper Triangular Matrix:\n", A)

Upper Triangular Matrix:
 [[1 2 3]
 [0 4 5]
 [0 0 6]]


# 3.9k Lower triangular matrix

In [47]:
# Lower triangular matrix
B = np.array([[1, 0, 0], [2, 3, 0], [4, 5, 6]])
print("Lower Triangular Matrix:\n", B)

Lower Triangular Matrix:
 [[1 0 0]
 [2 3 0]
 [4 5 6]]


# 3.9l Symmetric matrix 

In [51]:
# Symmetric matrix example
symmetric_matrix = np.array([[1, 2, 3], 
                             [2, 4, 5], 
                             [3, 5, 6]])

# Check if the matrix is symmetric (A == A^T)
is_symmetric = np.array_equal(symmetric_matrix, symmetric_matrix.T)

# Print the matrix and whether it's symmetric
print("Symmetric Matrix:\n", symmetric_matrix)
print("Is the matrix symmetric?", is_symmetric)

Symmetric Matrix:
 [[1 2 3]
 [2 4 5]
 [3 5 6]]
Is the matrix symmetric? True


# 3.9m Transpose of a matrix

In [55]:
# Transpose of a matrix
C = np.array([[1, 2], [3, 4], [5, 6]])
transpose_C = np.transpose(C)
print("Original Matrix:\n", C)
print("Transpose of Matrix:\n", transpose_C)

Original Matrix:
 [[1 2]
 [3 4]
 [5 6]]
Transpose of Matrix:
 [[1 3 5]
 [2 4 6]]


# 3.9n Idempotent matrix example

In [59]:
# Idempotent matrix example
D = np.array([[2/3, -1/3], [-1/3, 2/3]])
idempotent_check = np.allclose(np.dot(D, D), D)
print("Idempotent Matrix:\n", D)
print("Is Idempotent:", idempotent_check)

Idempotent Matrix:
 [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
Is Idempotent: False


# 3.9n Orthogonal matrix

In [63]:
# Orthogonal matrix example
E = np.array([[1, 0], [0, -1]])
orthogonal_check = np.allclose(np.dot(E.T, E), np.eye(2))
print("Orthogonal Matrix:\n", E)
print("Is Orthogonal:", orthogonal_check)

Orthogonal Matrix:
 [[ 1  0]
 [ 0 -1]]
Is Orthogonal: True


#  3.9n Unitary matrix example (complex numbers)

In [67]:
# Unitary matrix example (complex numbers)
F = np.array([[1/np.sqrt(2), 1j/np.sqrt(2)], [-1j/np.sqrt(2), 1/np.sqrt(2)]])
unitary_check = np.allclose(np.dot(np.conjugate(F.T), F), np.eye(2))
print("Unitary Matrix:\n", F)
print("Is Unitary:", unitary_check)

Unitary Matrix:
 [[ 0.70710678+0.j          0.        +0.70710678j]
 [-0.        -0.70710678j  0.70710678+0.j        ]]
Is Unitary: False


#  3.9n Involutory matrix example

In [71]:
# Involutory matrix example
G = np.array([[0, 1], [1, 0]])
involutory_check = np.allclose(np.dot(G, G), np.eye(2))
print("Involutory Matrix:\n", G)
print("Is Involutory:", involutory_check)

Involutory Matrix:
 [[0 1]
 [1 0]]
Is Involutory: True


#  3.9n Singular matrix example (determinant = 0)

In [75]:
# Singular matrix example (determinant = 0)
H = np.array([[1, 2], [2, 4]])
det_H = np.linalg.det(H)
is_singular = np.isclose(det_H, 0)
print("Singular Matrix:\n", H)
print("Determinant:", det_H)
print("Is Singular:", is_singular)

Singular Matrix:
 [[1 2]
 [2 4]]
Determinant: 0.0
Is Singular: True


#  3.9n Non-singular matrix example (determinant ≠ 0)

In [79]:
# Non-singular matrix example (determinant ≠ 0)
I = np.array([[1, 2], [3, 4]])
det_I = np.linalg.det(I)
is_non_singular = not np.isclose(det_I, 0)
print("Non-Singular Matrix:\n", I)
print("Determinant:", det_I)
print("Is Non-Singular:", is_non_singular)

Non-Singular Matrix:
 [[1 2]
 [3 4]]
Determinant: -2.0000000000000004
Is Non-Singular: True


# 3.9o Adjoint of a Matrix

In [83]:
# Example matrix
matrix = np.array([[1, 2], 
                   [3, 4]])

# Function to calculate the cofactor matrix
def cofactor_matrix(matrix):
    # Calculate the determinant of the matrix
    det = np.linalg.det(matrix)
    
    # If determinant is zero, adjoint does not exist
    if det == 0:
        return None
    
    # Calculate the cofactor matrix (using minor matrix and determinant)
    cofactors = []
    for i in range(matrix.shape[0]):
        row = []
        for j in range(matrix.shape[1]):
            # Minor matrix: remove row i and column j
            minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
            cofactor = (-1)**(i+j) * np.linalg.det(minor)
            row.append(cofactor)
        cofactors.append(row)
    
    # Return the cofactor matrix
    return np.array(cofactors)

# Compute the cofactor matrix
cofactors = cofactor_matrix(matrix)

# If cofactor matrix exists, compute the adjoint (transpose of cofactor matrix)
if cofactors is not None:
    adjoint = cofactors.T
    print("Adjoint of the Matrix:\n", adjoint)
else:
    print("Adjoint does not exist (determinant is 0)")

Adjoint of the Matrix:
 [[ 4. -2.]
 [-3.  1.]]


# 3.9p Addition

In [87]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
addition = A + B
print("Addition:\n", addition)

Addition:
 [[ 6  8]
 [10 12]]


# 3.9p Subtraction

In [91]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Subtraction
subtraction = A - B

print("Subtraction:\n", subtraction)

Subtraction:
 [[-4 -4]
 [-4 -4]]


# 3.9q Element-wise multiplication

In [95]:
# Element-wise multiplication
elementwise_multiplication = A * B
print("Element-wise Multiplication:\n", elementwise_multiplication)

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


# 3.9r Matrix multiplication (dot product)

In [99]:
# Matrix multiplication (dot product)
matrix_multiplication = np.dot(A, B)
print("Matrix Multiplication (Dot Product):\n", matrix_multiplication)

Matrix Multiplication (Dot Product):
 [[19 22]
 [43 50]]


# 3.9s Determinant

In [103]:
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: -2.0000000000000004


In [106]:
# Example 3x3 matrix
A = np.array([[1, 2, 3],
              [0, 4, 5],
              [1, 0, 6]])

# Determinant of A
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: 22.000000000000004


# 3.9t Inverse of a matrix

In [110]:
# Inverse of a matrix
inverse_A = np.linalg.inv(A)
print("Inverse of A:\n", inverse_A)

Inverse of A:
 [[ 1.09090909 -0.54545455 -0.09090909]
 [ 0.22727273  0.13636364 -0.22727273]
 [-0.18181818  0.09090909  0.18181818]]


# 3.9u Minor of an Element a_{ij}​  in ∣𝐴∣

In [114]:
def minor(matrix, i, j):
    # Delete the i-th row and j-th column
    submatrix = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    return np.linalg.det(submatrix)

# Calculate the minor of the element at position (0, 0) in A
minor_00 = minor(A, 0, 0)
print("Minor of element a[0][0]:", minor_00)

Minor of element a[0][0]: 23.999999999999993


# 3.9v Cofactor of an Element a_{ij}​ in ∣𝐴∣

In [118]:
def cofactor(matrix, i, j):
    # Calculate the minor
    minor_val = minor(matrix, i, j)
    # Apply the sign factor (-1)^(i+j)
    return (-1) ** (i + j) * minor_val

# Calculate the cofactor of the element at position (0, 0) in A
cofactor_00 = cofactor(A, 0, 0)
print("Cofactor of element a[0][0]:", cofactor_00)

Cofactor of element a[0][0]: 23.999999999999993


# 3.9w Trace

In [122]:
# Trace of a matrix (sum of diagonal elements)
trace_A = np.trace(A)
print("Trace of A:", trace_A)

Trace of A: 11


# 3.9x Eigenvalues and eigenvectors

In [126]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)

Eigenvalues of A: [7.04096459 1.08849669 2.87053872]
Eigenvectors of A:
 [[ 0.47577536  0.92699459 -0.56767265]
 [ 0.75149246  0.3241272  -0.80302126]
 [ 0.45705239 -0.18873948  0.18139628]]


# 3.9y Singular Value Decomposition

In [130]:
# Singular Value Decomposition
U, S, V = np.linalg.svd(A)
print("U:\n", U)
print("Singular values:", S)
print("V:\n", V)

U:
 [[-0.40084967 -0.17846775 -0.89859268]
 [-0.67585203 -0.6045742   0.42156148]
 [-0.61850107  0.77629846  0.12172558]]
Singular values: [9.06066469 3.04438047 0.79756061]
V:
 [[-0.11250287 -0.38684882 -0.91525466]
 [ 0.19637188 -0.9115918   0.36116267]
 [-0.974054   -0.13909844  0.17852292]]
